# Site Build settings
remote_theme: pages-themes/time-machine@v0.2.0
plugins: jekyll-remote-theme
gem "github-pages", group: :jekyll_plugins
title: Bridgette Bryant's Github Portfolio
description: A collection of all my repositories with neat descriptions and links.
show_downloads: false
